image: docker:latest

before_script:
  - docker login -u "$ALIYUN_DOCKER_USERNAME" -p "$ALIYUN_DOCKER_PASSWORD" $ALIYUN_DOCKER_REGISTRY

build-php56:
  stage: build
  script:
    - docker build -f Dockerfile.php56 -t "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-5.6" .
    - docker push "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-5.6"
  tags:
    - IDG

build-php70:
  stage: build
  script:
    - docker build -f Dockerfile.php70 -t "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.0" .
    - docker push "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.0"
  tags:
    - IDG

build-php71:
  stage: build
  script:
    - docker build -f Dockerfile.php71 -t "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.1" .
    - docker push "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.1"
  tags:
    - IDG

build-php72:
  stage: build
  script:
    - docker build -f Dockerfile.php72 -t "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.2" .
    - docker push "$ALIYUN_DOCKER_REGISTRY/itfarm/lnmp:php-7.2"
  tags:
    - IDG

